### ISSUE TITLE
Jak przetłumaczyć Title ?

### ISSUE THREAD

**Issue by postscripter8** [postscripter8/czeska_ustawa_o_broni#1]
Część pierwsza ustawy otwiera się słowami:

```
TITLE I
INTRODUCTORY PROVISIONS
```

Jak przetłumaczyć słowo `title` użyte w takim kontekście? Tymczasowo zostawię po prostu `tytuł`, ale w jęz. polskim brzmi to dosyć nienaturalnie.

**Comment by postscripter8** [comment]
W tekście oryginalnym w jęz. czeskim w tym miejscu występuje słowo `hlava`, co znaczy `głowa`. Może lepiej będzie przetłumaczyć na `nagłówek`?

**Comment by just-browsin** [comment]
Logicznie by pasował "rozdział".

**Comment by postscripter8** [comment]
@just-browsin No pasowałby jak ulał. Dzięki za podpowiedź!

**Comment by postscripter8** [comment]
Konwencja tłumaczenia nazw części składowych struktury dokumentu została zapisana w pliku na stronie wiki [Nazwy własne używane w ustawie i jej tłumaczenia](https://github.com/postscripter8/czeska_ustawa_o_broni/wiki/Nazwy-w%C5%82asne-u%C5%BCywane-w-ustawie-i-jej-t%C5%82umaczenia).
