### ISSUE TITLE
sekcja 8, 9, 10, 11, 12

### ISSUE THREAD

**Issue by just-browsin** [postscripter8/czeska_ustawa_o_broni#10]
Rozdział  III
Pozyskiwanie, posiadanie i noszenie broni palnej i amunicji;
artykuł 8
Tylko osoby posiadające pozwolenie na broń lub licencję na broń mogą pozyskiwać, za wyjątkiem dziedziczenia(art/sekcja 66), posiadać lub nosić broń lub amunicję, o ile nie zostało to inaczej określone w niniejszych przepisach.
artykuł 9
(1)	Zabronione jest pozyskiwanie, posiadanie lub noszenie broni palnej kategorii A, o ile nie zostało to inaczej określone w poniższych przepisach. Zakaz określony w pierwszym zdaniu nie dotyczy eksportu i importu na podstawie osobnych przepisów. 1) 
(2)	Policja Republiki Czeskiej (dalej "Policja") może zezwolić  w drodze wyjątku posiadaczowi pozwolenia na broń dla grup A lub licencji na grupy A, F, G, H, I, lub J, jeżeli ten posiadacz:
a)	jest kolekcjonerem lub bierze udział w działaniach związanych z muzealnictwem ;
b)	transportuje, strzeże wyjątkowo niebezpieczne lub wartościowe dobra, lub strzeże wyjątkowo ważnych miejsc, lub miejsc istotnych dla obronności kraju;
c)	wytwarza lub prowadzi podobną działalność, lub prowadzi testy, w których konieczna jest broń kategorii A; 
d)	naucza lub prowadzi treningi strzeleckie przy użyciu broni kategorii A; lub
e)	działa w branży filmowej lub teatralnej; W takich wypadkach broń palna będzie nieodwracalnie przerobiona w sposób gwarantujący, że jedynie ślepa lub ćwiczebna amunicja może zostać użyta;
Zezwolenie w drodze wyjątku moze zostać wydane o ile nie jest to sprzeczne z porządkiem i bezpieczeństwem publicznym, oraz moze zostać wydane na ograniczony okres, jeśli jest wydane w przypadkach opisanych w literach b) do e).
(3) Uprzednia zgoda Ministerstwa Obrony jest konieczna do wydania zezwolenia w drodze wyjątku na pozyskanie lub posiadanie broni określonej w art.4 (a) (1) (sprzęt wojskowy), podlegającej szczególnej kontroli zgodnie z porozumieniami międzynarodowymi będącymi częścią narodowego systemu prawnego.

artykuł 10
(1)	Posiadacz pozwolenia na broń grupy A lub licencji na broń grup  A, F, G, H, I lub J wnioskuje o zezwolenie w drodze wyjątku określone w art.9 zgodnie z wzorem pisma określonym w odrębnych przepisach wykonawczych. Pismo według wzoru musi zawierać:
a)	Imię, nazwisko, nazwisko panieńskie, datę i miejsce urodzenia, miejsce zamieszkania osoby fizycznej (dalej "dane osobowe"), lub pełną nazwę, formę prawną, siedzibę i numer identyfikacyjny osoby prawnej (dalej "dane identyfikacyjne osoby prawnej");
b)	typ broni palnej, nazwę handlową wytwórcy broni, model, kaliber i numer seryjny egzemplarza broni palnej, jeśli są znane wnioskodawcy (dalej "dane broni");
c)	typ zakazanej amunicji, nazwę handlową wytwórcy, kaliber i ilość amunicji (liczbę nabojów), w przypadku wniosku o zezwolenie w drodze wyjątku na pozyskanie, posiadanie lub noszenie zakazanej amunicji; 
d)	typ zakazanych akcesoriów do broni palnej wraz z ich opisem lub numerami seryjnymi;  
e)	numer (posiadanego) pozwolenia na broń lub licencji na broń; oraz 
f)	powód i cel (uzasadnienie) wnioskowania o zezwolenie w drodze wyjątku. 
(2)	Wnioski składa się w Komendzie Wojewódzkiej Policji właściwej ze względu na miejsce zamieszkania wnioskodawcy-osoby fizycznej lub siedzibę wnioskodawcy-osoby prawnej(dalej "właściwa jednostka policji").
 (3) Posiadacz pozwolenia na broń grupy A, zamieszkujący w kraju członkowskim Unii Europejskiej, dowolnym innym kraju członkowskim Europejskiego Obszaru Ekonomicznego, lub Konfederacji Szwajcarskiej (dalej "państwo członkowski"), jest zobowiązany do przedłożenia zgody państwa członkowskiego na wniosek o zezwolenie w drodze wyjątku określonego w par.(1) lub oświadczenie o niewymaganiu takiej zgody (przez państwo członkowskie). Dokument ma być przetłumaczony na język czeski przez certyfikowanego tłumacza figurującego w Rejestrze Ekspertów Kryminalnych i Tłumaczy.

Artykuł 11
(1)	Zezwolenie w drodze wyjątku udzielone na podstawie Art. 9 (2) wygasa i traci moc w przypadku:
a)	upłynięcia terminu jego ważności;
b)	utraty przez wnioskodawcę pozwolenia na broń grupy A lub licencji na broń grup   A, F, G, H, I lub J .
(2)	Zezwolenie w drodze wyjątku zostanie cofnięte, jeśli powód jego wydania przestaje istnieć.
(3) Jezeli zezwolenie w drodze wyjątku wygasa z przyczyn określonych w par. (1), lub zostaje cofnięte z przyczyn opisanych w par. (2), posiadacz pozwolenia na bron grupy A jest zobowiązany do dostarczenia i przekazania broni palnej której dotyczyło zezwolenie w drodze wyjątku, do właściwej jednostki policji w terminie nie przekraczającym 10 dni roboczych od daty wejścia w życie decyzji o cofnięciu zezwolenia, lub daty jego wygaśnięcia. Postępowanie posiadacza pozwolenia określa artykuł/sekcja 64 niniejszego aktu.

Artykuł 12
(1)	Broń kategorii B może być pozyskana, posiadana i noszona wyłącznie na podstawie zezwolenia, o ile dalsze przepisy nie stanowią inaczej. 
(2)	Wyłącznie posiadacz pozwolenia lub licencji na broń może pozyskiwać, posiadać lub nosić amunicję do broni kategorii B, za zezwoleniem zgodnie z określoną grupą pozwolenia/licencji. 
(3)	Posiadacz pozwolenia na broń lub licencji na broń wnioskuje o zezwolenie opisane w par. (1) na piśmie zgodnie z wzorem określonym w przepisach wykonawczych. Wniosek musi zawierać:
a)	dane osobowe lub dane identyfikacyjne osoby prawnej;
b)	dane broni; nazwę wytwórcy, model, kaliber i numer seryjny, jeśli są znane wnioskodawcy;
c)	numer pozwolenia lub licencji na broń; oraz
d)	uzasadnienie wniosku.
(4)	posiadacz pozwolenia na broń, zamieszkujący w państwie członkowskim Un, jest zobowiązany do przedłożenia zgody państwa członkowskiego na wniosek o zezwolenie określone w par.(1) lub oświadczenie o niewymaganiu takiej zgody (przez państwo członkowskie). Dokument ma być przetłumaczony na język czeski przez certyfikowanego tłumacza figurującego w Rejestrze Ekspertów Kryminalnych i Tłumaczy.
(5)	Właściwa jednostka policji wydaje zezwolenie na pozyskanie lub posiadanie broni kategorii B wyłącznie w uzasadnionych przypadkach. Za uzasadniony przypadek uważa się:
a)	wnioskodawca jest kolekcjonerem lub prowadzi działalność związaną z muzealnictwem;
b)	wnioskodawca bierze udział w aktywności sportowej, łowieckiej, kulturowej lub podobnych działaniach, lub szkoli się zawodowo (w tych kierunkach);
c)	wnioskodawca prowadzi przedsiębiorstwo handlowe lub inną działalność gospodarczą na podstawie osobnej koncesji dotyczącej broni i amunicji;
d)	wnioskodawca strzeże własności lub osób (ochrona fizyczna);
e)	wnioskodawca wykonuje czynności określone odrębnymi przepisami; lub
f)	broń jest do celu ochrony życia, zdrowia lub własności.
(6) Właściwa jednostka policji wydaje zezwolenie na noszenie broni kategorii B jeżeli wnioskodawca w uzasadnieniu poda którykolwiek z powodów opisanych w par. (5) litera (b) (c) (d) (e), lub (f) 
(7)	Zezwolenie opisane w par. (5) i (6) zostanie wydane na wniosek w postaci jednej decyzji. Takie zezwolenie może zostać wydane razem z decyzją nadającą pozwolenie lub licencję na broń.
(8)	Zezwolenie na noszenie broni kategorii B zostaje odnotowane w pozwoleniu na broń.

**Comment by postscripter8** [comment]
`acquisition` przetłumaczyłbym raczej na `nabywanie`. Jak sądzisz?

**Comment by postscripter8** [comment]
@just-browsin Dlaczego w artykule 9 par. (1) zakończyłeś odniesieniem `1)`? W oryginale i w tekście angielskim jest `9)`. Zostawie `9)`, ok?

**Comment by postscripter8** [comment]
Tłumaczenie sekcji 8~12 dodane w plikach:

  - [part_1/title_III/sekcja_8_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_8_PL.md)
  - [part_1/title_III/sekcja_9_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_9_PL.md)
  - [part_1/title_III/sekcja_10_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_10_PL.md)
  - [part_1/title_III/sekcja_11_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_11_PL.md)
  - [part_1/title_III/sekcja_12_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_12_PL.md)

**Comment by just-browsin** [comment]
Odniesienie zostawiłem złe przez pomyłkę, dzięki za wychwycenie.
Nie upieram się przy "pozyskiwaniu", "nabywanie" też jest logiczne i w sumie lepiej pasuje.

**Comment by postscripter8** [comment]
Dzięki za tłumaczenie - bardzo dobra robota.

Tymczasem skoro nie ma wątpliwości to issue zamykam. Jakby były jakieś uwagi, zawsze można otworzyć, albo utworzyć nowe.
