### ISSUE TITLE
sekcje 13, 14, 15

### ISSUE THREAD

**Issue by just-browsin** [postscripter8/czeska_ustawa_o_broni#11]
Artykuł 13
(1)	Zezwolenie wydane na podstawie art. 12 traci ważność, jeśli jego posiadacz utraci pozwolenie lub licencję na broń. Zezwolenie na zakup broi kategorii B traci ważność, jeśli broń kategorii B nie została zakupiona na jego podstawie w ciągu 12 miesięcy od daty wydania.
(2)	Właściwa jednostka policji cofa zezwolenie wydane na podstawie art. 12, jeśli ustanie powód wymieniony w uzasadnieniu wniosku. Niniejszy przepis nie dotyczy zezwoleń wydanych na podstawie art. 12 par.(5) (f).
 (3) W przypadku utraty ważności zezwolenia w sposób opisany w pierwszym zdaniu par. (1), posiadacz broni kategorii B jest zobowiązany do dostarczenia i przekazania tej broni właściwej jednostce policji w ciągu 10 dni roboczych od daty utraty ważności zezwolenia lub daty wejścia w życie decyzji o cofnięciu zezwolenia. Postępowanie posiadacza pozwolenia określa artykuł/sekcja 64 niniejszego aktu.
 
artykuł 14
Broń kategorii C moze być pozyskana lub posiadana wyłącznie przez posiadacza pozwolenia na broń odpowiedniej grupy, lub licencji na bron odpowiedniej grupy. Posiadacz pozwolenia lub licencji na broń jest zobowiązany do zgłoszenia zakupu broni kategorii C odpowiedniej jednostce policji. Posiadacz pozwolenia na broń może nosić broń kategorii C jedynie w zakresie zezwoleń w ramach określonej grupy pozwoleń, po dokonaniu zgłoszenia/rejestracji (artykuł 41).

artykuł 15
(1)	Broń palną kategorii D lub amunicję do niej mogą pozyskiwać i posiadać wyłącznie osoby fizyczne mające ponad 18 lat, o pełnej zdolności do czynności prawnych. Broń kategorii D lub amunicję do niej mogą pozyskiwać i posiadać takze osoby prawne. 
(2)	Broń wymieniona w art. 7 (a) lub (b) może być używana wyłącznie na strzelnicach, za wyjątkiem przedstawień teatralnych, rekonstrukcji historycznych i podobnych wydarzeń kulturalnych, podczas których nie dochodzi do wystrzeliwania pocisków. Taka broń będzie odpowiednio oznaczona na podstawie odrębnych przepisów.3)
(3)	 Strzelanie z broni wymienionych w 7 (c) do (g) lub wymienionych w art. 7 (k) jest zabronione w miejscach w których mogłoby stworzyć zagrożenie dla życia lub zdrowia osób postronnych, lub zagrożenie uszkodzeniem mienia.
(4)	Posiadacz broni kategorii D jest zobowiązany zabezpieczyć ją i amunicję do niej przed utratą, kradzieżą i nadużyciem.
(5)	Posiadaczowi broni kategorii D nie wolno:
a)	nosić broni w sposób widoczny w miejscach publicznych lub ogólnodostępnych;
b)	nosić broni lub operować nią w miejscach publicznych lub ogólnodostępnych, jeśli jego zdolność do noszenia broni została obniżona spożyciem alkoholu, użyciem substancji odurzających, leków lub z powodu choroby;
c)	przenieść praw własności do broni kategorii D lub amunicji do niej na osobę nieuprawnioną, lub pozostawić je takiej osobie

Uwaga - angielskie tłumaczenie w 15 (5) (c) mówi o limicie na składowanie prochu i spłonek, nie ma tego w dokumencie czeskim, patrz https://www.zakonyprolidi.cz/cs/2002-119#cast1

**Comment by postscripter8** [comment]
Tłumaczenie dodane w plikach:

  - [part_1/title_III/sekcja_13_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_13_PL.md)
  - [part_1/title_III/sekcja_14_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_14_PL.md)
  - [part_1/title_III/sekcja_15_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_III/sekcja_15_PL.md)
