### ISSUE TITLE
Sekcja 20

### ISSUE THREAD

**Issue by kozikadze** [postscripter8/czeska_ustawa_o_broni#21]
Section 20
Health Capability to be Issued a Firearm Permit 
**Wymagania medyczne do wydania pozwolenia na broń**
(1) An assessing physician shall issue a certificate regarding the health capability of an applicant for a firearm permit on the basis of a medical examination or, as the case may be,  on the basis of a psychological examination and other necessary tests. For the purposes of this Act the assessing physician shall be a family doctor with whom the applicant for a firearm permit or the firearm permit holder is registered for medical care; in the case of  an applicant for a firearm permit for group D, the assessing physician shall be a doctor at a medical facility providing preventive medical care to the relevant employer.
**Lekarz oceniający wyda certyfikat / zaświadczenie dotyczące stanu zdrowia aplikanta na podstawie badania medycznego lub jeżeli występuje taka potrzeba na podstawie badania psychologicznegoi innych nezbednych testów. Na potrzeby tego aktu prawnego lekarzem oceniającym będzie lekarz rodzinny aplikanta starającego się  lub  posiadającego pozwolenie “na broń”; w przypadku aplikanta starającego się o pozwolenie dla grupy “D” lekarzem oceniającym będzie lekarz pracy przypisany danemu pracodawcy**
(2) A firearm permit holder for groups D and F shall be obliged to submit him/herself to a medical examination by an assessing physician within one month after 30 months have elapsed since the date on which the relevant firearm permit was issued.
**Posiadacz pozwolenia na broń grupy D i F jest zobowiązany do stawienia się na badania medyczne u lekarza orzekającego w ciągu miesiąca po 30 miesiącach od kiedy zostało mu wydanye pozwolenie na broń – rewizyta po otrzymaniu kwitów :)**
(3) Should an assessing physician find any change to the health condition of a firearm permit holder the consequence of which is the loss of health capability, the physician shall be obliged to issue a new certificate regarding health capability and send it, without undue delay, to the relevant police unit. As regards the holder of a firearm permit for group D, the physician shall be also obliged to inform, without undue delay, the employer of the permit holder.
**Jeżeli lekarz orzekający wykryje jakieś zmiany w zdrowiu posiadacza pozwolenia zoobowiązany jest wystawić nowe orzeczenie lekarskie dotyczące faktycznego stanu zdrowia posiadacza I bez zwłoki wysłać je do odpowiedniego organu policji. Jeżeli chodzi o posiadaczy pozwolenia typu D w tym przypadku lekarz orzekający zobowiazany jest niezwłocznie wysłać orzeczenie do pracodawcy posiadacza tego pozwolenia.**
(4) Any doctor who finds evidence or who has reasonable suspicion that a firearm permit holder suffers from a disease or impairment or is in a condition excluding or limiting the option to possess or carry a firearm, must instruct such holder of such facts and must inform, without undue delay, an assessing physician of the facts.  The assessing physician concerned shall proceed in compliance with paragraph 3.
**Którykolwiek lekarz znajdzie dowody lub ma uzasadnione podejrzenia, że posiadacz pozwolenia cierpi na jakąś chorobę, ograniczenie lub jest w stanie wykluczajacym lub ograniczającym jego opcje posiadania czy noszenia broni musi poinformować posiadacza pozwolenia o takim fakcie oraz poinformować bez zwłoki lekarza orzekającego. Lekarz orzekający w takim przypadku postąpi zgodnie z paragrafem 3.**
(5) In those cases referred to in paragraph 3 the firearm permit holder shall be obliged to appear in person, upon the invitation of the assessing physician, on the specified date, before the physician concerned and submit to a medical examination of health capability prior to being issued a new firearm permit. If the firearm permit holder cannot submit to a medical examination due to serious reasons he/she shall be obliged to do so not later than within one month from the date specified by the assessing physician. If a firearm permit holder does not submit to a medical examination the assessing physician shall inform, without undue delay, the relevant police unit thereof.
**W przypadkach opisanych w paragrafie 3 posiadacz pozwolenia jest zoobligowany do stawienia się w wyznaczonym terminie przed lekarzem orzekającym aby poddać się badaniom lekarskim oceniającym zdolność do posiadania broni w celu uzyskania nowego pozwolenia na broń. Jeżeli osoba wezwana na badania medyczne nie może stawić się w wyznaczonej dacie z jakichś ważnych przyczyn jest zobligowana na stawienie się u lekarza orzekającego nie później niż w ciągu miesiąca od daty wyznaczenia wizyty na którą nie mógł się stawić. Jeżeli posiadacz pozwolenia nie stawi się u lekarza orzekającego ten bez zwłoki poinformuje o tym odpowiedzialny wydział policji.**
(6) Requirements for health capability pursuant to paragraph 1, types of medical examinations, their content, the content of a medical certification and the period of validity, description of diseases, impairments and health conditions for which it is impossible to issue a positive opinion and or where such opinion may be issued only if the holder is examined by a medical specialist, shall be stipulated in an implementing legal regulation.
**Wymagania zdolności zdrowia ( medyczne po polskiemu :) zgodnie z paragrafem 1. typy badań medycznych, ich treść, zawartość i ważność, ocena chorób, niezdolności i stan zdrowia dla którego nie da się wystawić pozytywnej opinii i / lub gdy taka opinia może być wystawiona wyłącznie przez lakarza specjalistę będzie określone przez przepisy prawne.**

**Comment by kopernik1elfka** [comment]
Pozwoliłam sobie przeformatować, poprawić kilka literówek, wykasować ostatni komentarz:

<a name="section_20"></a><p align="center">Rozdział 20<br /> Wymagania medyczne do wydania pozwolenia na broń</p>

(1) Lekarz oceniający wyda certyfikat / zaświadczenie dotyczące stanu zdrowia aplikanta na podstawie badania medycznego lub jeżeli występuje taka potrzeba na podstawie badania psychologicznego i innych niezbędnych testów. Na potrzeby tego aktu prawnego lekarzem oceniającym będzie lekarz rodzinny aplikanta starającego się lub posiadającego pozwolenie “na broń”; w przypadku aplikanta starającego się o pozwolenie dla grupy “D” lekarzem oceniającym będzie lekarz pracy przypisany danemu pracodawcy

(2) Posiadacz pozwolenia na broń grupy D i F jest zobowiązany do stawienia się na badania medyczne u lekarza orzekającego w ciągu miesiąca po upływie 30 miesięcy od kiedy zostało mu wydane pozwolenie na broń. _[rewizyta po otrzymaniu kwitów :), przyp. tłumacza]_

(3) Jeżeli lekarz orzekający wykryje jakieś zmiany w zdrowiu posiadacza pozwolenia zobowiązany jest wystawić nowe orzeczenie lekarskie dotyczące faktycznego stanu zdrowia posiadacza i bez zwłoki wysłać je do odpowiedniego organu policji. Jeżeli chodzi o posiadaczy pozwolenia typu D w tym przypadku lekarz orzekający zobowiązany jest niezwłocznie wysłać orzeczenie do pracodawcy posiadacza tego pozwolenia.


(4) Którykolwiek lekarz znajdzie dowody lub ma uzasadnione podejrzenia, że posiadacz pozwolenia cierpi na jakąś chorobę, ograniczenie lub jest w stanie wykluczającym lub ograniczającym jego opcje posiadania czy noszenia broni musi poinformować posiadacza pozwolenia o takim fakcie oraz poinformować bez zwłoki lekarza orzekającego. Lekarz orzekający w takim przypadku postąpi zgodnie z paragrafem 3.



(5) W przypadkach opisanych w paragrafie 3 posiadacz pozwolenia jest zobligowany do stawienia się w wyznaczonym terminie przed lekarzem orzekającym aby poddać się badaniom lekarskim oceniającym zdolność do posiadania broni w celu uzyskania nowego pozwolenia na broń. Jeżeli osoba wezwana na badania medyczne nie może stawić się w wyznaczonej dacie z jakichś ważnych przyczyn jest zobligowana na stawienie się u lekarza orzekającego nie później niż w ciągu miesiąca od daty wyznaczenia wizyty na którą nie mógł się stawić. Jeżeli posiadacz pozwolenia nie stawi się u lekarza orzekającego ten bez zwłoki poinformuje o tym odpowiedzialny wydział policji.



(6) Wymagania medyczne zgodnie z paragrafem 1. typy badań medycznych, ich treść, zawartość i ważność, ocena chorób, niezdolności i stan zdrowia dla którego nie da się wystawić pozytywnej opinii i / lub gdy taka opinia może być wystawiona wyłącznie przez lekarza specjalistę będzie określone przez przepisy prawne.

**Comment by kozikadze** [comment]
Spoko. Żaden ze mnie AS tłumeczeń :P nie wspomnę już o języku polskim.

**Comment by postscripter8** [comment]
Wygląda wcale w porządku. Wrzucam do projektu. Dzięki za pomoc!
