### ISSUE TITLE
part_1/title_IX/sekcja_60_PL do szlifu po zebraniu wszystkiego w kupe

### ISSUE THREAD

**Issue by Purpurowyserzkosmosu** [postscripter8/czeska_ustawa_o_broni#7]
Sekcja 60

Posiadanie i przenoszenie broni podczas eventów, imprez masowych i rozrywkowych (i w miejscach zgromadzeń?)

Osoba uczestniczaca/biorąca udział w publicznym zgromadzeniu, festiwalu, zawodach sportowych, imprezie mającej charakter rozrywkowym może posiadać i przenosić broń jedynie w wypadkach gdy:

a) Przenosi broń w celu rekreacyjnego strzelania na strzelnicach i/lub przystosowanych do strzelectwa obiektów;

b) Bierze udział, za pozwoleniem organizatora w zabezpieczaniu imprezy sportowej której część ma charakter strzelecki;

c) Spełnia wymagania formalne wymienione w 10) ;

d) W wypadku gdy jest to niezbędne do ochrony życia, zdrowia uczestników zgromadzenia lub ochrony mienia/posiadłości/budynku/konstrukcji w momencie gdy regionalne biuro Policji odpowiadajace za zabezpieczenie miejsca eventu wyraziło zgodę na przenoszenie broni na danym obszarze.

**Comment by postscripter8** [comment]
Podtytuł tego artykułu w oryginale `Držení a nošení zbraní při zvláštních příležitostech`.
Coś w rodzaju `Posiadanie i noszenie broni podczas specjalnych okoliczności`.

**Comment by postscripter8** [comment]
Co do `c)` mam pewne obiekcje. Przypis 10 `For example Act No. 553/1991 Coll. on the municipal police, as amended.` - mowa o straży gminnej. W oryginale jest `zabezpečuje-li úkoly podle zvláštního právního předpisu` -> _google translate_ -> `Jeśli zadania są świadczone przez specjalne przepisy prawne` --> _moim zdaniem_ -> `wykonuje zadania określone w innych przepisach`.

**Comment by postscripter8** [comment]
Dodałem tłumaczenie w pliku [part_1/title_IX/sekcja_60_PL.md](https://github.com/postscripter8/czeska_ustawa_o_broni/blob/master/part_1/title_IX/sekcja_60_PL.md). Zmieniłem sformułowania w literach `c)` i `d)`, żeby bardziej dosłownie odzwierciedlały oryginał czeski.

**Comment by Purpurowyserzkosmosu** [comment]
Primo! 
Postaram się przetłumaczyć pare nastepnych artukułów dzisiaj jak znajdę dłuższą chwilkę
